name: build-development-workflow
on:
  push:
  pull_request:
  workflow_dispatch:


## OIDC Configuration
permissions:
    id-token: write
    contents: read
    deployments: write
    statuses: write
    
jobs:
  build:
    uses: mdnahidmondol/shared-github-actions/.github/workflows/java-spring-build-push-dockerhub.yml@main
    secrets: inherit
    with:
      CONTAINER_IMAGE_NAME: sample-spring-boot-app
      IMAGE_TAG: sha-${{ github.sha }}
      DOCKER_REPOSITORY: rudder9290