name: release
on:
  workflow_dispatch:

## OIDC Configuration
permissions:
    id-token: write
    contents: read
    deployments: write
    statuses: write

jobs:
    release:
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        uses: mdnahidmondol/shared-github-actions/.github/workflows/release.yml@main
        secrets: inherit
        with:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
