name: release
on:
  workflow_dispatch:

## OIDC Configuration
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
    release:
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        uses: mdnahidmondol/shared-github-actions/.github/workflows/release.yml@main
        secrets:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}